### ISSUE TITLE
Add Multi-Thread Support

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/dem2mesh#1]
When multiple tiles are being processed, the user should be able to choose to process multiple tiles in parallel.

This will increase memory usage.

**Comment by petergerten** [comment]
Did anyone work on multi-thread support yet? This is currently the bottleneck in my pipeline.

**Comment by pierotofy** [comment]
Not that I'm aware of; we'd welcome a PR!

**Comment by pierotofy** [comment]
Well I just couldn't resist adding this. :)
